#ifndef __DEFINITIONS_SCENE_H__
#define __DEFINITIONS_SCENE_H__

#define DISPLAY_TIME_SPASH_SCENE 2
#define TRANSITION_TIME 0.5
#define PIPE_SPAWN_FREQUENCY 0.005

#define PIPE_GAP 10
#define UPPER_SCREEN_PIPE_THRESHOLD 0.65
#define LOWER_SCREEN_PIPE_THRESHOLD 0.35

#define PIPE_MOVEMENT_SPEED 0.01

#define BIRD_COLLISION_BITMASK 0x000001 
#define OBSTACLE_COLLISION_MASK 0x000002

#endif // __DEFINITIONS_SCENE_H__
