#ifndef __DEFINITIONS_SCENE_H__
#define __DEFINITIONS_SCENE_H__

#define DISPLAY_TIME_SPASH_SCENE 2
#define TRANSITION_TIME 0.5
#define PIPE_SPAWN_FREQUENCY 0.0007

#define PIPE_GAP 3
#define UPPER_SCREEN_PIPE_THRESHOLD 0.65
#define LOWER_SCREEN_PIPE_THRESHOLD 0.35

#define PIPE_MOVEMENT_SPEED 0.01

#define BIRD_COLLISION_BITMASK 0x000001 
#define OBSTACLE_COLLISION_MASK 0x000002
#define SCORE_COLLISION_MASK 0x000003

#define BIRD_FALLING_SPEED 0.0075
#define BIRD_FLYING_SPEED 0.01375
#define BIRD_FLY_DURATION 0.25
#define WIND_POWER 0.0050
#define MOVE_POWER 0.03

#define SCORE_FONT_SIZE 0.1

#endif // __DEFINITIONS_SCENE_H__
